
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package a95compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 23;
  public static final int FUNCTION = 3;
  public static final int MULT = 39;
  public static final int PUT = 26;
  public static final int LEFTP = 41;
  public static final int CASE = 17;
  public static final int SEMIC = 31;
  public static final int INTEGER = 27;
  public static final int OUT = 14;
  public static final int FOR = 12;
  public static final int NOT = 43;
  public static final int IS = 5;
  public static final int IN = 13;
  public static final int BOOL = 30;
  public static final int COMMA = 33;
  public static final int GET = 25;
  public static final int BEGIN = 6;
  public static final int LOOP = 16;
  public static final int EXIT = 22;
  public static final int ASSIGN = 36;
  public static final int IF = 8;
  public static final int ID = 18;
  public static final int DECIMALS = 21;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 35;
  public static final int error = 1;
  public static final int ADD = 40;
  public static final int IN_OUT = 15;
  public static final int NULL = 24;
  public static final int NUMBER = 19;
  public static final int LOGIC_OP = 37;
  public static final int COLON = 32;
  public static final int ELSE = 10;
  public static final int NEW_LINE = 34;
  public static final int STRINGTYPE = 28;
  public static final int FLOAT = 29;
  public static final int THEN = 9;
  public static final int END = 7;
  public static final int STRING = 20;
  public static final int RIGHTP = 42;
  public static final int ELIF = 11;
  public static final int PROCEDURE = 2;
  public static final int RELATE = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "FUNCTION",
  "RETURN",
  "IS",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ELIF",
  "FOR",
  "IN",
  "OUT",
  "IN_OUT",
  "LOOP",
  "CASE",
  "ID",
  "NUMBER",
  "STRING",
  "DECIMALS",
  "EXIT",
  "WHEN",
  "NULL",
  "GET",
  "PUT",
  "INTEGER",
  "STRINGTYPE",
  "FLOAT",
  "BOOL",
  "SEMIC",
  "COLON",
  "COMMA",
  "NEW_LINE",
  "EQUAL",
  "ASSIGN",
  "LOGIC_OP",
  "RELATE",
  "MULT",
  "ADD",
  "LEFTP",
  "RIGHTP",
  "NOT"
  };
}

